logging:
  level:
    root: INFO

server.port: 8080
springdoc:
  api-docs:
    path: /api/auth/docs
  swagger-ui:
    path: /api/auth/swagger
    operations-sorter: method
  packages-to-scan: edu.ntnu.idatt2105.g6.backend.controller





spring:
  profiles:
    active: dev

